import { defineConfig, type Plugin } from 'vite';
import { createReadStream, existsSync, statSync } from 'node:fs';
import { resolve, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('.', import.meta.url));

/**
 * Baked world data lives in `data/baked/` (gitignored, regenerated by `pnpm bake`).
 * It is served at `/world/*`. Worktrees can point MOW_WORLD_DIR at the main checkout's
 * data/baked so agents never need to re-bake.
 */
const WORLD_DIR = resolve(process.env.MOW_WORLD_DIR ?? join(ROOT, 'data', 'baked'));

function serveWorldData(): Plugin {
  const types: Record<string, string> = {
    '.json': 'application/json',
    '.bin': 'application/octet-stream',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.webp': 'image/webp',
  };
  return {
    name: 'mome-serve-world-data',
    configureServer(server) {
      server.middlewares.use('/world', (req, res, next) => {
        const rel = decodeURIComponent((req.url ?? '/').split('?')[0]);
        const file = normalize(join(WORLD_DIR, rel));
        if (!file.startsWith(WORLD_DIR) || !existsSync(file) || !statSync(file).isFile()) return next();
        const ext = file.slice(file.lastIndexOf('.'));
        res.setHeader('Content-Type', types[ext] ?? 'application/octet-stream');
        res.setHeader('Cache-Control', 'no-cache');
        createReadStream(file).pipe(res);
      });
    },
  };
}

export default defineConfig({
  plugins: [serveWorldData()],
  resolve: {
    dedupe: ['three'],
  },
  // only crawl the app entry: the default **/*.html scan would walk agent worktrees (.claude/) and venvs
  optimizeDeps: {
    entries: ['index.html'],
    // loaded by a dynamic import (src/landmarks/model.ts): pre-bundle it so a fresh dependency cache never
    // answers the first capture with "504 Outdated Optimize Dep"
    include: ['three/addons/loaders/GLTFLoader.js'],
  },
  server: {
    port: Number(process.env.PORT ?? 5173),
    strictPort: true,
    watch: {
      ignored: ['**/data/**', '**/reference/**', '**/renders/**', '**/tools/bake/**', '**/.venv/**', '**/.cache/**', '**/.git/**', '**/docs/**', '**/.claude/**'],
    },
  },
  build: {
    target: 'es2023',
    sourcemap: true,
    chunkSizeWarningLimit: 4000,
  },
});
