import type { EmitterPreset } from '../landmarks/records.ts';

/**
 * Effect presets (S4 W3-E): the static behaviour of every emitter kind the EffectsSystem realizes.
 * Lengths are km per unit of the emitter's `scale` (which already carries the landmark's design scale),
 * times are seconds of the effect clock (env.tFx / SceneState.tFx). Colours are linear albedo.
 *
 * Particle families (particles.ts):
 *  - plume  smoke, steam: a buoyant column that rises with a decaying velocity, widens, bends downwind
 *           and — under an ash deck — flattens and spreads under the ceiling (an umbrella that fades into
 *           the pall, so the plume merges into the deck with no plane intersection); a declared smoke
 *           below WISP_SCALE is a thin `wisp` (a chimney, an Isengard pit)
 *  - ash    broad, thin ash clouds drifting downwind under the deck from the plume (or from `at` to `to`:
 *           low sheets over a plain)
 *  - spray  the spray cloud at a waterfall's foot (generated by the falls, not declared); a wide fall
 *           (Rauros) also raises a tall `steam` mist column over its foot
 *  - mist / beam  static geometry (mist cards, the Morgul beam) — no particles
 *  - embers / sparks  additive points handed to the EmissionSystem (setDynamic): beacon flames, crater sparks
 */

/** The particle families of the billboard draw. */
export type PuffFamily = 'plume' | 'ash' | 'spray';

export interface PuffPreset {
  family: PuffFamily;
  /** puffs at rate 1, scale 1 (× rate × scale^COUNT_EXP, at quality density 1) */
  count: number;
  /** fewest puffs of a drawn emitter */
  minCount: number;
  /** seconds per puff life (× scale^LIFE_EXP: big plumes billow slowly) */
  life: number;
  /** free rise (km per scale; a deck ceiling caps it) */
  rise: number;
  /** column radius at the source and at the top of its free rise (km per scale) */
  r0: number;
  r1: number;
  /** umbrella (under a ceiling): its final radius as a multiple of r1, and its share of the life */
  spread: number;
  umbrella: number;
  /** downwind drift of the column top as a fraction of its rise, and of the umbrella (km per scale) */
  bend: number;
  drift: number;
  /** puff radius at birth and at the top (km per scale) */
  size0: number;
  size1: number;
  /** base opacity of one puff (the atlas density multiplies it) */
  opacity: number;
  /** linear albedo (the emitter's `color` overrides it) */
  albedo: [number, number, number];
  /** how much of the spill (lava / fires near the source) the puffs take: lit from below */
  spill: number;
  /** 0..1: the puffs dissolve as they rise (steam, chimney smoke) instead of keeping their density */
  dissolve: number;
  /** projected extent (px) below which the emitter is not drawn, and above which it gets all its puffs */
  lodPx: [number, number];
  /** the scale the counts and lives are tuned at (count ∝ (scale / refScale)^COUNT_EXP); default 1 */
  refScale?: number;
  /** edge softness 0..3 (0: a billowing smoke edge, 3: a diffuse spray / steam cloud); default 0 */
  soft?: number;
}

/** instance capacity of the puff draw (all drawn emitters together) */
export const MAX_PUFFS = 4096;

/** puff count ∝ scale^COUNT_EXP (a big plume gets more puffs, not only bigger ones) */
export const COUNT_EXP = 0.6;
/** puff life ∝ scale^LIFE_EXP */
export const LIFE_EXP = 0.3;

/** the billboard presets the EffectsSystem realizes ('wisp' = a declared smoke below WISP_SCALE) */
export type PuffKind = 'smoke' | 'wisp' | 'ash' | 'steam' | 'spray';

/** a declared `smoke` emitter with a scale below this is a thin wisp (a chimney), not a column */
export const WISP_SCALE = 0.15;

/**
 * The billboard presets. Doom's smoke (scale 3) is a ≈ 4.5 km wide column at the crater widening to
 * ≈ 20 km, rising ≈ 19 km into the deck and spreading under it, with ≈ 420 puffs at density 1;
 * Barad-dûr's / the Black Gate's / Isengard's smokes (0.9 … 1.6) are dark columns dissolving a few km up;
 * a chimney (≈ 0.04) is a thin wisp bending downwind.
 */
export const PUFF: Record<PuffKind, PuffPreset> = {
  smoke: {
    family: 'plume',
    count: 220,
    minCount: 6,
    life: 30,
    rise: 6,
    r0: 0.75,
    r1: 3.8,
    spread: 2.1,
    umbrella: 0.32,
    bend: 0.5,
    drift: 2.6,
    size0: 0.5,
    size1: 1.9,
    opacity: 0.5,
    albedo: [0.2, 0.185, 0.17],
    spill: 1,
    dissolve: 0.45,
    lodPx: [36, 140],
  },
  wisp: {
    family: 'plume',
    count: 44,
    minCount: 10,
    life: 18,
    rise: 5.5,
    r0: 0.25,
    r1: 1.5,
    spread: 1,
    umbrella: 0,
    bend: 0.5,
    drift: 0,
    size0: 0.55,
    size1: 1.8,
    opacity: 0.4,
    albedo: [0.5, 0.51, 0.53],
    spill: 0.08,
    dissolve: 0.6,
    lodPx: [12, 60],
    soft: 2,
    refScale: 0.04,
  },
  ash: {
    family: 'ash',
    count: 30,
    minCount: 4,
    life: 70,
    rise: 2.4,
    r0: 0.15,
    r1: 0.5,
    spread: 1,
    umbrella: 0,
    bend: 0,
    drift: 4.5,
    size0: 0.22,
    size1: 0.55,
    opacity: 0.32,
    albedo: [0.14, 0.132, 0.125],
    spill: 0.5,
    dissolve: 0,
    lodPx: [60, 200],
    soft: 2,
  },
  steam: {
    family: 'plume',
    count: 36,
    minCount: 5,
    life: 16,
    rise: 3.2,
    r0: 0.1,
    r1: 0.75,
    spread: 2,
    umbrella: 0.3,
    bend: 0.5,
    drift: 1.5,
    size0: 0.12,
    size1: 0.7,
    opacity: 0.5,
    albedo: [0.62, 0.62, 0.63],
    spill: 0.6,
    dissolve: 0.75,
    lodPx: [30, 120],
    soft: 2,
  },
  spray: {
    family: 'spray',
    count: 30,
    minCount: 4,
    life: 9,
    rise: 1.2,
    r0: 0.22,
    r1: 0.9,
    spread: 1,
    umbrella: 0,
    bend: 0.4,
    drift: 0,
    size0: 0.3,
    size1: 1.0,
    opacity: 0.5,
    albedo: [0.86, 0.88, 0.9],
    spill: 0.4,
    dissolve: 0.6,
    lodPx: [10, 80],
    soft: 3,
  },
};

/** Every declared preset the EffectsSystem understands (the check flags anything else). */
export const KNOWN_PRESETS: readonly EmitterPreset[] = ['smoke', 'ash', 'embers', 'steam', 'mist', 'sparks', 'beam'];

/**
 * The plume / umbrella stays this far (km) under the deck height and its puffs fade out before they
 * reach it: the pall carries on where the plume stops (no plane intersection).
 */
export const DECK_MARGIN = 1.6;
/** deck cover (atmosphere.deckAt) above which an emitter has a ceiling */
export const DECK_CEILING_COVER = 0.3;
/** a plume whose free rise reaches this share of the ceiling height rises all the way and spreads under it */
export const CAP_REACH = 1.6;

/** Sparks / embers (EmissionSystem dynamic lights): counts at rate 1, life, reach (km per scale). */
export const SPARKS = { count: 24, life: 2.6, rise: 0.9, spread: 0.6, radiusKm: 0.012, intensity: 3.2, lodPx: [40, 140] as [number, number] };
export const EMBERS = { flames: 5, sparks: 8, life: 1.6, rise: 0.22, radiusKm: 0.03, intensity: 4, lodPx: [3, 24] as [number, number] };

/**
 * Mist cards: layers, the vertical spacing as a fraction of the half-width, grid resolution, opacity, the
 * projected card width (px) over which a card fades in (wide shots: the atmosphere's valley mist takes over)
 * and the share of the background a card veils (alpha × occlusion; its in-scatter is added in full).
 */
export const MIST = { layers: 3, spacing: 0.06, maxSpacing: 0.18, grid: [16, 8] as [number, number], opacity: 0.9, lodPx: [12, 60] as [number, number], occlusion: 0.65 };

/** The Morgul beam: core / glow half-widths (km per scale), HDR radiance, linear colour. */
export const BEAM = { core: 0.05, glow: 0.6, radiance: 14, color: [0.32, 1, 0.5] as [number, number, number], segments: 32 };

/**
 * Waterfalls: ribbon segments, the veil layer's width ratio, plunge-foam radius (× the fall's size) and its
 * rings / sectors, how far the curtain turns toward the camera around its axis (0 = flat on its path,
 * 1 = an axis billboard: a fall seen along its wall never collapses to a thread), the draped falls'
 * visual widening, the width from which a fall raises a tall mist column over its foot (Rauros: the "smoke"
 * of the falls, seen behind the Argonath) and that column's scale per km of width, how much longer than
 * wide the curtain's streaks are, and the foot spray's scale: max(min(sprayWidth · width, sprayMax),
 * sprayDrop · drop) (a wide fall's spray stays a cloud at its foot, the mist column carries the rest; a
 * tall thin fall still throws a big cloud).
 */
export const FALLS = { segments: 24, veil: 1.35, foam: 0.75, foamRings: 4, foamSectors: 24, facing: 0.45, drapeWiden: 1.4, columnWidth: 2, column: 0.55, streakStretch: 3, sprayMax: 2.5, sprayWidth: 1.4, sprayDrop: 0.25 };

/** per-frame key-visibility slots of the falls / mist cards materials (uniform arrays; more draw lit) */
export const FX_VIS_SLOTS = 16;
